//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrderTbRestaurant.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Food
    {
        public long ID { get; set; }
        public Nullable<long> Food_ID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> OrderTable_ID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual OrderTable OrderTable { get; set; }
    }
}
