//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrderTbRestaurant.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Menu
    {
        public long ID { get; set; }
        public string Content { get; set; }
        public string Link { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
