//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrderTbRestaurant.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTable()
        {
            this.Book_Food = new HashSet<Book_Food>();
        }
    
        public long ID { get; set; }
        public string Full_Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string DateBook { get; set; }
        public string TimeBook { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Count_people { get; set; }
        public string Description { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Food> Book_Food { get; set; }
        public virtual User User { get; set; }
    }
}
